#!/bin/sh

# TODO: timestamp checking

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
gunzip --stdout uniprot_sprot.fasta.gz > uniprot_sprot.fasta

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz
gunzip --stdout uniprot_trembl.fasta.gz > uniprot_trembl.fasta

cat uniprot_sprot.fasta uniprot_trembl.fasta > uniprot_sprot_trembl.fasta

formatdb -p T -t uniprot_sprot_trembl -n uniprot_sprot_trembl -i uniprot_sprot_trembl.fasta
formatdb -p T -t uniprot_sprot -n uniprot_sprot -i uniprot_sprot.fasta
formatdb -p T -t uniprot_trembl -n uniprot_trembl -i uniprot_trembl.fasta

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
gunzip --stdout uniprot_sprot.xml.gz > uniprot_sprot.xml

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.xml.gz
gunzip --stdout uniprot_trembl.xml.gz > uniprot_trembl.xml

run_annotation_parse_uniprot_xml.pl uniprot_sprot.xml uniprot_trembl.xml
