#!/bin/sh

# TODO: timestamp checking

wget --continue http://www.mgc.ac.cn/VFs/Down/VFs.xls.gz http://www.mgc.ac.cn/VFs/Down/VFs.ffn.gz http://www.mgc.ac.cn/VFs/Down/VFs.faa.gz http://www.mgc.ac.cn/VFs/Down/Comparative_tables_from_VFDB.tar.gz http://www.mgc.ac.cn/VFs/Down/CP_VFs.ffn.gz http://www.mgc.ac.cn/VFs/Down/CP_VFs.faa.gz

echo "Extracting..."

for i in `ls VFs*.gz CP_VFs*.gz`; do file=`basename $i .gz`;  gunzip --stdout $i >$file; done

formatdb -p T -t vfdb_CP_VFs_aa -n vfdb_CP_VFs_aa -i CP_VFs.faa -o T
formatdb -p F -t vfdb_CP_VFs_nt -n vfdb_CP_VFs_nt -i CP_VFs.ffn -o T
formatdb -p T -t vfdb_VFs_aa -n vfdb_VFs_aa -i VFs.faa -o T
formatdb -p F -t vfdb_VFs_nt -n vfdb_VFs_nt -i VFs.ffn -o T
