#!/bin/sh

# (optional) fsfind database

# annotation stage - VFDB
update_vfdb
if [ $? -gt 0 ]; then exit $?; fi

# isFinder database
update_is -o is
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - COGS
update_cogs
if [ $? -gt 0 ]; then exit $?; fi

# protein databank
update_pdb
if [ $? -gt 0 ]; then exit $?; fi

# antimicrobial resistance targets
update_card.sh
if [ $? -gt 0 ]; then exit $?; fi
update_argannot.sh
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - uniprot+sprot
update_uniprot
if [ $? -gt 0 ]; then exit $?; fi

