#!/bin/bash

echo `basename $0`": BEGIN Updating uniprot. This could take a while."

# Get the fasta databases
if [ ! -f "uniprot_sprot.fasta.gz" ]; then
  echo `basename $0`": Downloading uniprot_sprot";
  wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz -O uniprot_sprot.fasta.gz.tmp && mv uniprot_sprot.fasta.gz.tmp uniprot_sprot.fasta.gz -v
  #gunzip -c uniprot_sprot.fasta.gz > uniprot_sprot.fasta
  if [ $? -gt 0 ]; then exit $?; fi
fi;

if [[ ! -f "uniprot_trembl.fasta.gz" ]]; then
  echo `basename $0`": Downloading uniprot_trembl";
  wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz -O uniprot_trembl.fasta.gz.tmp && mv -v uniprot_trembl.fasta.gz.tmp uniprot_trembl.fasta.gz
  if [ $? -gt 0 ]; then exit $?; fi
fi;

if [[ ! -f "uniprot_sprot.fasta" ]]; then
  echo `basename $0`": Formatting the sprot database to make a gene prediction database; the output is also going to be filtered and made nonredundant."
  run_annotation_parse_uniprot_fasta.pl uniprot_sprot.fasta.gz > uniprot_sprot.fasta.tmp && mv -v uniprot_sprot.fasta.tmp uniprot_sprot.fasta
  if [ $? -gt 0 ]; then exit $?; fi
fi

# We don't really need trembl by itself. Concat it with Swiss-prot
if [[ ! -f "uniprot_sprot_trembl.fasta" ]]; then
  echo `basename $0`": Concatenating the trembl database with uniprot database to make a comprehensive database; the output is also going to be filtered and made nonredundant."
  run_annotation_parse_uniprot_fasta.pl uniprot_sprot.fasta.gz uniprot_trembl.fasta.gz > uniprot_sprot_trembl.fasta.tmp && mv uniprot_sprot_trembl.fasta.tmp uniprot_sprot_trembl.fasta -v;
  if [ $? -gt 0 ]; then exit $?; fi;
fi;

echo `basename $0`": Formatting the sprot and uniprot fasta files as databases for blast"
makeblastdb -dbtype prot -in uniprot_sprot.fasta
if [ $? -gt 0 ]; then exit $?; fi
makeblastdb -dbtype prot -in uniprot_sprot_trembl.fasta
if [ $? -gt 0 ]; then exit $?; fi

echo `basename $0`": Getting XML descriptions of sprot and uniprot"
wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
gunzip uniprot_sprot.xml.gz uniprot_sprot.xml

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.xml.gz
gunzip uniprot_trembl.xml.gz uniprot_trembl.xml

echo `basename $0`": Parsing XML descriptions of sprot and uniprot"
run_annotation_parse_uniprot_xml.pl uniprot_sprot.xml uniprot_trembl.xml
rm -v uniprot_sprot.xml uniprot_trembl.xml
echo `basename $0`": FINISHED Updating uniprot."

