#!/bin/sh

# (optional) fsfind database

# isFinder database
update_is -o is
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - VFDB
update_vfdb
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - COGS
update_cogs
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - uniprot+sprot
update_uniprot
if [ $? -gt 0 ]; then exit $?; fi


# annotation stage - PDB (not implemented in annotation yet)
update_pdb
if [ $? -gt 0 ]; then exit $?; fi
