#!/bin/sh

echo `basename $0`": BEGIN Updating uniprot. This could take a while."

# Get the fasta databases
if [ ! -f "uniprot_sprot.fasta" ]; then
  wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
  gunzip -c uniprot_sprot.fasta.gz > uniprot_sprot.fasta
  if [ $? -gt 0 ]; then exit $?; fi
fi;

if [ ! -f "uniprot_trembl.fasta" ]; then
  wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz
  gunzip -c uniprot_trembl.fasta.gz > uniprot_trembl.fasta
  if [ $? -gt 0 ]; then exit $?; fi
fi;

# We don't really need trembl by itself. Concat it with Swiss-prot
echo "Concatenating the tremble database with uniprot database to make a comprehensive database"
cat uniprot_sprot.fasta uniprot_trembl.fasta > uniprot_sprot_trembl.fasta
if [ $? -gt 0 ]; then 
  rm -v uniprot_sprot_trembl.fasta; 
  exit $?; 
fi

echo "Filtering the sprot and uniprot databases for just bacterial genera";
run_annotation_parse_uniprot_fasta.pl uniprot_sprot.fasta > uniprot_sprot.fasta.filtered && mv -v uniprot_sprot.fasta.filtered uniprot_sprot.fasta
if [ $? -gt 0 ]; then exit $?; fi
run_annotation_parse_uniprot_fasta.pl prot_sprot_trembl.fasta > uniprot_sprot_trembl.fasta.filtered && mv -v uniprot_sprot_trembl.fasta.filtered uniprot_sprot_trembl.fasta
if [ $? -gt 0 ]; then exit $?; fi

echo "Formatting the sprot and uniprot databases"
legacy_blast.pl formatdb -p T -t uniprot_sprot_trembl -n uniprot_sprot_trembl -i uniprot_sprot_trembl.fasta
legacy_blast.pl formatdb -p T -t uniprot_sprot -n uniprot_sprot -i uniprot_sprot.fasta

echo "Getting XML descriptions of sprot and uniprot"
wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
gunzip uniprot_sprot.xml.gz uniprot_sprot.xml

wget --continue ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.xml.gz
gunzip uniprot_trembl.xml.gz uniprot_trembl.xml

echo "Parsing XML descriptions of sprot and uniprot"
run_annotation_parse_uniprot_xml.pl uniprot_sprot.xml uniprot_trembl.xml
rm -v uniprot_sprot.xml uniprot_trembl.xml
echo `basename $0`": FINISHED Updating uniprot."

