#!/bin/sh

outfile=pdb_seqres.faa
url=ftp://ftp.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt.gz

echo "Downloading and extracting PDB database from $url";

wget --continue $url -q -O - | gunzip -c > $outfile

legacy_blast.pl formatdb -p T -i $outfile

echo "Done getting pdb!";
