#!/bin/sh

# (optional) fsfind database

# isFinder database
update_is -o is
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - VFDB
update_vfdb
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - VFDB
update_cogs
if [ $? -gt 0 ]; then exit $?; fi

# annotation stage - uniprot+sprot
update_uniprot
if [ $? -gt 0 ]; then exit $?; fi

