#!/usr/bin/env perl

# Check for functionality of required and optional dependencies.

use strict;
use FindBin;
use lib "$FindBin::RealBin/../lib";
$ENV{PATH} = "$FindBin::RealBin:".$ENV{PATH};

use AKUtils;

# Required dependencies:
# bioperl newbler glimmer3 amoscmp 

my $bioperl_ok = 0;
foreach my $prefix (@INC) {
	$bioperl_ok = 1 if -f "$prefix/Bio/Perl.pm";
}
die(makeDepFailMsg("BioPerl")) unless $bioperl_ok;

my $newbler_ok = 0;
$newbler_ok = 1 if (AKUtils::fullPathToExec("runMapping")
	and AKUtils::fullPathToExec("runAssembly")
	and AKUtils::fullPathToExec("sfffile"));
die(makeDepFailMsg("454 Newbler")) unless $newbler_ok;

my $amos_ok = 0;
$amos_ok = 1 if (AKUtils::fullPathToExec("mummer")
	and AKUtils::fullPathToExec("AMOScmp"));
die(makeDepFailMsg("AMOScmp")) unless $amos_ok;

my $glimmer3_ok = 1;
foreach my $exefile (qw(long-orfs extract build-icm glimmer3)) {
	$glimmer3_ok = 0 unless AKUtils::fullPathToExec($exefile);
}
die(makeDepFailMsg("glimmer3")) unless $glimmer3_ok;

my $gmhmm_ok = 1;
foreach my $exefile (qw(gmsn.pl gmhmmp)) {
	$gmhmm_ok = 0 unless AKUtils::fullPathToExec($exefile);
}
die(makeDepFailMsg("GeneMarkHMM")) unless $gmhmm_ok;




sub makeDepFailMsg($;$) {
	my ($dep_name, $optional) = @_;
	my $project_name = "cg_pipeline";
	return "A dependency check for $dep_name failed. $dep_name is "
		.($optional ? "an optional" : "a required")
		." dependency of $project_name. Please check your installation.\n";
}
